version: '3.8'

services:
    nginx:
        image: nginx:latest
        container_name: nginx-proxy
        ports:
            - "80:80"  # Порт для доступа через NGINX
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf  # Конфигурация NGINX
        depends_on:
            - car-request-service  # NGINX стартует после приложения
        networks:
            - app-network

    car-request-service:
        build:
            context: ./car-request-service
            dockerfile: Dockerfile
        container_name: car-request-service
        ports:
            - "8080:8080"  # Открываем порт для приложения
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
